### ISSUE TITLE
섹션 3. 템플릿 메서드 패턴과 콜백 패턴

### ISSUE THREAD

**Issue by janeljs** [codesquad-study/spring-core-advanced#3]
## 스터디 날짜: 1/4(화) PM 09:00
강의 주제 또는 공유하고 싶은 주제를 자유롭게 공유 ✌🏻

**Comment by sanhee** [comment]
앗 깜박했는데 감사해요!

**Comment by janeljs** [comment]
@sanhee 항상 만들어주고 구글 미트 파줘서 고마워요ㅎㅎ

**Comment by sanhee** [comment]
동 발표자료
- https://github.com/d-h-k/Spring_PlayGround/blob/main/spring-advenced/advenced/%ED%95%99%EC%8A%B5%EC%A0%95%EB%A6%AC.md
